"""Add icon column to categories

Revision ID: 3460b0b3f660
Revises: 736cb13a4d4e
Create Date: 2025-10-27 11:10:44.752894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3460b0b3f660'
down_revision: Union[str, None] = '736cb13a4d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'icon')
    # ### end Alembic commands ###
