"""add_location_payment_method_and_status_logs

Revision ID: ae78ac682481
Revises: 30d8815225ba
Create Date: 2025-10-04 03:51:08.022829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae78ac682481'
down_revision: Union[str, None] = '30d8815225ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero_banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hero_banners_id'), 'hero_banners', ['id'], unique=False)
    op.create_table('order_status_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=False),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('changed_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_logs_id'), 'order_status_logs', ['id'], unique=False)
    op.add_column('orders', sa.Column('location', sa.Text(), nullable=False))
    op.add_column('orders', sa.Column('payment_method', sa.Enum('mpesa', 'whatsapp', name='paymentmethod'), nullable=True))
    op.drop_column('orders', 'address')
    op.drop_column('orders', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('city', sa.VARCHAR(), nullable=False))
    op.add_column('orders', sa.Column('address', sa.TEXT(), nullable=False))
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'location')
    op.drop_index(op.f('ix_order_status_logs_id'), table_name='order_status_logs')
    op.drop_table('order_status_logs')
    op.drop_index(op.f('ix_hero_banners_id'), table_name='hero_banners')
    op.drop_table('hero_banners')
    # ### end Alembic commands ###
