"""Add icon to categories

Revision ID: ff5d6a52c4f0
Revises: 3460b0b3f660
Create Date: 2025-10-27 11:40:04.374735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5d6a52c4f0'
down_revision: Union[str, None] = '3460b0b3f660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
